name: Mineslate
version: 1.0.1
author: Nir Vaknin
main: org.games4peace.mineslate.Main
api-version: 1.13

permissions:
  Mineslate.globalListen:
    description: Allows a player to listen to all char disregarding chat groups
    default: op